apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: retain-gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3