apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql #name of statefulset
spec:
  serviceName: mysql #mustmatch with headless service name
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpass
            - name: MYSQL_DATABASE
              value: appdb
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data  #volume name. any name can be given
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: retain-gp3
        resources:
          requests:
            storage: 5Gi